### ISSUE TITLE
GUI Shutting Down while Generating Prediction

### ISSUE THREAD

**Issue by jobthoma97** [rifqiharrys/sdb_gui#10] opened 2024-11-07 10:25 UTC
Hey @rifqiharrys !

Thank you for this tool.

I am using the SDB_GUI latest release 3.6.1.

The problem that I faced was, the tools close automatically while generating the prediction. It runs upto 42 percent then it exits the GUI and closes the CMD prompt.

It would be very helpful if I get some suggestions on this error.

Thank you in advance!!!

Screenshot of the process before closing the GUI: 
![Error](https://github.com/user-attachments/assets/fd56990d-617d-4c2f-8fc7-dd94816c05db)

**Comment by rifqiharrys** [comment] 2024-11-14 12:42
Hey @jobthoma97.
Sorry for the late reply. I have been occupied with work lately.
The most common error when I use the tool is out of memory because the satellite image file was too big.
Or you could see the error in the console (prompt). 
Run the .exe file using console (powershell or cmd) to prevent it closing after the error occurs.

Test it using *Multi Linear Regression* for faster processing time.
I hope this helps.
Cheers.

**Comment by jobthoma97** [comment] 2024-11-17 08:11
Hey @rifqiharrys ,

Sorry for troubling you and thank you very much for the reply.

I'll try to follow the suggestions which you have suggested.

 Thank you!!!

**Comment by jobthoma97** [comment] 2024-11-18 06:47
Hey @rifqiharrys ,

I tried clipping the image and the depth sample data, to make it small in size.

Even after doing that, the GUI is closing after 42 percent.

It's showing the following error: 
![Screenshot 2024-11-18 154456](https://github.com/user-attachments/assets/27fa5901-4f59-4bf9-83e4-e00768765371)

**Comment by rifqiharrys** [comment] 2024-11-26 04:18
Hey @jobthoma97 ,
The processing failure might be caused by wrong selection of some dropdown menu or depth limit entry.
And that depends on your understanding of your data.

Try example data in /notebook/data. The depth data is positive down, meaning depth under 0 vertical datum has positive sign. So, depth direction dropdown menu is selected as positive down (red rectangle).
Meanwhile in depth limit entry (green rectangle), depth limitation is in positive up paradigm.

![image](https://github.com/user-attachments/assets/6bca6199-760f-4de8-913d-ee7650da732f)

**Comment by jobthoma97** [comment] 2024-12-02 06:07
Hello @rifqiharrys ,

Thank you for the suggestions.
It worked.
I had depth points in positive and I set the depth direction to "Positive Up", hence the issue. 

Thank you for the valuable directions!!!

**Comment by rifqiharrys** [comment] 2024-12-02 07:34
Hello @jobthoma97 ,

Thank you for your feedback. I'm glad it works.
I really need to rework the workflow in readme file a bit more detail it seems, haha

**Closed** 2024-12-02 07:35 UTC
